import type { Product } from '@/types';

export const products: Product[] = [
  {
    sku: 'TDS-GRM-200',
    title: 'Authentic Ghee Roast Masala',
    category: 'grocery',
    sub_category: 'spices-masalas',
    price: 150,
    sale_price: 129,
    currency: 'INR',
    weight: '200g',
    stock_qty: 50,
    stock_status: 'instock',
    description: 'A traditional blend of spices from the coastal region of Karnataka, perfect for making the famous Chicken Ghee Roast. Made with roasted red chillies and a secret mix of aromatic spices, this masala brings the authentic taste of Karavali to your kitchen.',
    short_description: 'Spicy and aromatic blend for authentic Ghee Roast.',
    images: ['product-1-1', 'product-1-2'],
    brand: 'Karavali Flavors',
    tags: ['masala', 'ghee roast', 'spices'],
    gst_rate: 5,
  },
  {
    sku: 'TDS-KMP-250',
    title: 'Kundapur Masala Powder',
    category: 'grocery',
    sub_category: 'spices-masalas',
    price: 130,
    currency: 'INR',
    weight: '250g',
    stock_qty: 30,
    stock_status: 'instock',
    description: 'A versatile masala powder from the town of Kundapur. This unique blend can be used for a variety of vegetarian and non-vegetarian dishes, lending a distinct, tangy, and spicy flavor profile.',
    short_description: 'Versatile and tangy masala for various dishes.',
    images: ['product-2-1'],
    brand: 'Coastal Spices',
    tags: ['masala', 'kundapur', 'spices'],
    gst_rate: 5,
  },
  {
    sku: 'TDP-MP-500',
    title: 'Homemade Mango Pickle',
    category: 'grocery',
    sub_category: 'pickles-condiments',
    price: 250,
    sale_price: 220,
    currency: 'INR',
    weight: '500g',
    stock_qty: 40,
    stock_status: 'instock',
    description: 'Spicy and tangy mango pickle made with raw mangoes and a blend of traditional spices in cold-pressed mustard oil. A perfect accompaniment to any Indian meal.',
    short_description: 'Tangy raw mango pickle, a mealtime essential.',
    images: ['product-3-1'],
    brand: 'Granny\'s Recipe',
    tags: ['pickle', 'mango', 'condiment'],
    gst_rate: 12,
  },
  {
    sku: 'TDSN-JC-150',
    title: 'Crispy Jackfruit Chips',
    category: 'snacks',
    price: 180,
    currency: 'INR',
    weight: '150g',
    stock_qty: 0,
    stock_status: 'outofstock',
    description: 'Crispy, savory chips made from ripe jackfruit, deep-fried in pure coconut oil. A healthy and delicious snack that captures the essence of coastal flavors.',
    short_description: 'Savory and crispy chips made from ripe jackfruit.',
    images: ['product-4-1'],
    brand: 'Karavali Crunch',
    tags: ['snacks', 'jackfruit', 'chips'],
    gst_rate: 12,
  },
  {
    sku: 'TDG-RR-1000',
    title: 'Boiled Red Rice (Kaje Akki)',
    category: 'grocery',
    sub_category: 'rice',
    price: 90,
    currency: 'INR',
    weight: '1kg',
    stock_qty: 100,
    stock_status: 'instock',
    description: 'Nutritious and wholesome boiled red rice, a staple in Karavali households. Its earthy flavor and firm texture make it a perfect pair for spicy curries.',
    short_description: 'Nutritious and earthy local red rice.',
    images: ['product-5-1'],
    brand: 'Local Harvest',
    tags: ['rice', 'red rice', 'grocery'],
    gst_rate: 0,
  },
  {
    sku: 'TDSN-BC-200',
    title: 'Spicy Banana Chips',
    category: 'snacks',
    price: 120,
    sale_price: 99,
    currency: 'INR',
    weight: '200g',
    stock_qty: 75,
    stock_status: 'instock',
    description: 'Thinly sliced Nendran bananas fried to perfection in coconut oil and sprinkled with a spicy masala mix. An irresistible snack for any time of the day.',
    short_description: 'Crispy Nendran banana chips with a spicy kick.',
    images: ['product-6-1'],
    brand: 'Karavali Crunch',
    tags: ['snacks', 'banana', 'chips'],
    gst_rate: 12,
  },
  {
    sku: 'TDN-CN-250',
    title: 'Premium Cashew Nuts',
    category: 'snacks',
    price: 350,
    currency: 'INR',
    weight: '250g',
    stock_qty: 60,
    stock_status: 'instock',
    description: 'High-quality, whole cashew nuts sourced from the finest farms in the region. Creamy, crunchy, and packed with nutrients.',
    short_description: 'Creamy and crunchy premium whole cashews.',
    images: ['product-7-1'],
    brand: 'Coastal Harvest',
    tags: ['snacks', 'nuts', 'cashew'],
    gst_rate: 5,
  },
  {
    sku: 'TDG-JG-500',
    title: 'Organic Palm Jaggery',
    category: 'grocery',
    sub_category: 'sweeteners',
    price: 180,
    currency: 'INR',
    weight: '500g',
    stock_qty: 45,
    stock_status: 'instock',
    description: 'Unrefined and organic jaggery made from palm sap. A healthy alternative to sugar with a rich, caramel-like flavor.',
    short_description: 'Rich, unrefined organic palm jaggery.',
    images: ['product-8-1'],
    brand: 'Local Harvest',
    tags: ['jaggery', 'sweetener', 'organic'],
    gst_rate: 0,
  },
  {
    sku: 'TDO-CO-500',
    title: 'Cold-Pressed Coconut Oil',
    category: 'grocery',
    sub_category: 'oils',
    price: 280,
    sale_price: 259,
    currency: 'INR',
    weight: '500ml',
    stock_qty: 55,
    stock_status: 'instock',
    description: '100% pure, cold-pressed coconut oil extracted from fresh coconuts. Ideal for cooking, hair, and skin care.',
    short_description: 'Pure, cold-pressed coconut oil for cooking and care.',
    images: ['product-9-1'],
    brand: 'Coastal Harvest',
    tags: ['oil', 'coconut oil', 'cooking'],
    gst_rate: 5,
  },
  {
    sku: 'TDP-AMP-300',
    title: 'Tender Mango Pickle (Appe Midi)',
    category: 'grocery',
    sub_category: 'pickles-condiments',
    price: 320,
    currency: 'INR',
    weight: '300g',
    stock_qty: 25,
    stock_status: 'instock',
    description: 'A rare and prized pickle made from tiny, fragrant tender mangoes (Appe Midi). This delicacy offers an intense, unmatched flavor.',
    short_description: 'Exquisite pickle from fragrant tender mangoes.',
    images: ['product-10-1'],
    brand: 'Granny\'s Recipe',
    tags: ['pickle', 'mango', 'appe midi'],
    gst_rate: 12,
  },
  {
    sku: 'TDH-SI-01',
    title: 'Sandalwood Ganesha Idol',
    category: 'household',
    sub_category: 'pooja-items',
    price: 1200,
    currency: 'INR',
    stock_qty: 15,
    stock_status: 'instock',
    description: 'Exquisitely carved Ganesha idol from authentic sandalwood. A piece of art that brings peace and prosperity to your home.',
    short_description: 'Hand-carved authentic sandalwood Ganesha.',
    images: ['product-11-1'],
    brand: 'Karavali Crafts',
    tags: ['handicraft', 'sandalwood', 'idol'],
    gst_rate: 12,
  },
  {
    sku: 'TDH-TP-01',
    title: 'Handmade Terracotta Pot',
    category: 'household',
    sub_category: 'kitchenware',
    price: 450,
    sale_price: 399,
    currency: 'INR',
    stock_qty: 20,
    stock_status: 'instock',
    description: 'A beautiful, eco-friendly terracotta pot, handcrafted by local potters. Ideal for planting or as a decorative piece.',
    short_description: 'Eco-friendly, handcrafted decorative pot.',
    images: ['product-12-1'],
    brand: 'Karavali Crafts',
    tags: ['handicraft', 'terracotta', 'pot'],
    gst_rate: 5,
  },
  {
    sku: 'TDA-TC-100',
    title: 'Triphala Churna',
    category: 'ayurvedic',
    price: 180,
    currency: 'INR',
    weight: '100g',
    stock_qty: 40,
    stock_status: 'instock',
    description: 'A classic Ayurvedic herbal formulation of Amla, Haritaki, and Bibhitaki. Known for its detoxifying and rejuvenating properties.',
    short_description: 'Ayurvedic digestive and detox support.',
    images: ['ayurvedic-1'],
    brand: 'Veda Essentials',
    tags: ['ayurvedic', 'triphala', 'wellness'],
    gst_rate: 12,
  },
  {
    sku: 'TDA-AC-100',
    title: 'Ashwagandha Capsules',
    category: 'ayurvedic',
    price: 250,
    currency: 'INR',
    stock_qty: 35,
    stock_status: 'instock',
    description: 'Potent Ashwagandha root extract in convenient capsule form. Helps in managing stress and promoting vitality.',
    short_description: 'Adaptogenic herb for stress relief and energy.',
    images: ['ayurvedic-2'],
    brand: 'Veda Essentials',
    tags: ['ayurvedic', 'ashwagandha', 'stress-relief'],
    gst_rate: 12,
  },
  {
    sku: 'TDR-SHV-200',
    title: 'Ready to Eat Rice Shavige',
    category: 'ready-to-eat',
    sub_category: 'shavige',
    price: 120,
    currency: 'INR',
    weight: '200g',
    stock_qty: 30,
    stock_status: 'instock',
    description: 'Instant rice vermicelli (Shavige) that is ready to be seasoned. Just soak in hot water and it\'s ready for your favorite lemon or tamarind seasoning.',
    short_description: 'Instant rice vermicelli for a quick meal.',
    images: ['ready-to-eat-1'],
    brand: 'Karavali Kitchen',
    tags: ['shavige', 'instant', 'ready-to-eat', 'breakfast'],
    gst_rate: 5,
  },
  {
    sku: 'TDR-PTR-004',
    title: 'Ready to Steam Patrode',
    category: 'ready-to-eat',
    sub_category: 'patrode',
    price: 150,
    currency: 'INR',
    stock_qty: 20,
    stock_status: 'instock',
    description: 'Colocasia leaves layered with a spiced rice and lentil batter, rolled and ready to be steamed. A traditional Karavali delicacy.',
    short_description: 'Spiced colocasia leaf rolls, ready to steam.',
    images: ['ready-to-eat-2'],
    brand: 'Karavali Kitchen',
    tags: ['patrode', 'ready-to-eat', 'snack'],
    gst_rate: 5,
  },
  {
    sku: 'TDR-KTE-006',
    title: 'Kotte Idli Batter',
    category: 'ready-to-eat',
    sub_category: 'kotte',
    price: 90,
    currency: 'INR',
    stock_qty: 40,
    stock_status: 'instock',
    description: 'Idli batter specially prepared to be steamed in jackfruit leaf baskets (Kotte). Enjoy the unique aroma and flavor of this traditional dish.',
    short_description: 'Batter for making aromatic Kotte idlis.',
    images: ['ready-to-eat-3'],
    brand: 'Karavali Kitchen',
    tags: ['kotte', 'idli', 'ready-to-eat', 'breakfast'],
    gst_rate: 5,
  },
   {
    sku: 'TDR-NDM-500',
    title: 'Neer Dose Batter',
    category: 'ready-to-eat',
    sub_category: 'neer-dose',
    price: 70,
    currency: 'INR',
    weight: '500ml',
    stock_qty: 50,
    stock_status: 'instock',
    description: 'Ready-to-use batter for making soft, thin, and lacy Neer Dosa. Just pour and cook for a delicious and light meal.',
    short_description: 'Fresh batter for lacy rice crepes.',
    images: ['ready-to-eat-4'],
    brand: 'Karavali Kitchen',
    tags: ['neer dose', 'dosa', 'ready-to-eat', 'breakfast'],
    gst_rate: 5,
  },
];
